<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akun_model extends CI_Model
{

    public $table = 'tbl_akun';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('nomor_induk', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('nomor_induk', $q);
        $this->db->or_like('pass', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        $this->db->order_by('status ASC');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('nomor_induk', $q);
        $this->db->or_like('pass', $q);
        $this->db->or_like('status', $q);
        $this->db->limit($limit, $start);
        $this->db->order_by('status ASC');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data,$data2)
    {
        $this->db->insert($this->table, $data);
        $this->db->insert('tbl_akun_detail', $data2);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where('nomor_induk', $id);
        $this->db->delete('tbl_akun');
        $this->db->where('nomor_induk', $id);
        $this->db->delete('tbl_akun_detail');
    }

}

/* End of file Akun_model.php */
/* Location: ./application/models/Akun_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-18 08:09:37 */
/* http://harviacode.com */