<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_Pengumuman extends CI_Model
{

    public $table = 'tbl_berita';
    public $id = 'berita_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->group_start();
        $this->db->or_like('berita_id', $q);
        $this->db->or_like('berita_judul', $q);
        $this->db->or_like('berita_isi', $q);
        $this->db->or_like('berita_image', $q);
        $this->db->or_like('pj', $q);
        $this->db->or_like('berita_tanggal', $q);
        $this->db->group_end();
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->group_start();
        $this->db->or_like('berita_id', $q);
        $this->db->or_like('berita_judul', $q);
        $this->db->or_like('berita_isi', $q);
        $this->db->or_like('berita_image', $q);
        $this->db->or_like('pj', $q);
        $this->db->or_like('berita_tanggal', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_dosen.php */
/* Location: ./application/models/M_dosen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-25 17:01:23 */
/* http://harviacode.com */