<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'tbl_mahasiswa';
    public $id = 'nim';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('tb_jurusan', 'tb_jurusan.id_jurusan = tbl_mahasiswa.id_jenjang');
        $this->db->join('tb_jenjang', 'tb_jenjang.id_jenjang = tb_jurusan.id_jenjang');
        $this->db->group_start();
        $this->db->or_like('nim', $q);
        $this->db->or_like('nik', $q);
        $this->db->or_like('nama_mhs', $q);
        $this->db->or_like('tempat_lahir_mhs', $q);
        $this->db->or_like('tgl_lahir_mhs', $q);
        $this->db->or_like('gender_mhs', $q);
        $this->db->or_like('asal_sma', $q);
        $this->db->or_like('agama_mhs', $q);
        $this->db->or_like('nama_ibu_kandung', $q);
        $this->db->or_like('sks_diakui', $q);
        $this->db->or_like('angkatan', $q);
        $this->db->or_like('nama_jurusan', $q);
        $this->db->or_like('id_beasiswa', $q);
        $this->db->or_like('nowa', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('alamat_a', $q);
        $this->db->or_like('alamat_s', $q);
        $this->db->or_like('nama_jenjang', $q);
        $this->db->or_like('id_st_msk', $q);  
        $this->db->or_like('asal_universitas', $q);
        $this->db->or_like('foto_mhs', $q);
        $this->db->group_end();
        $this->db->where('status', '1');
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('tb_jurusan', 'tb_jurusan.id_jurusan = tbl_mahasiswa.id_jenjang');
        $this->db->join('tb_jenjang', 'tb_jenjang.id_jenjang = tb_jurusan.id_jenjang');
        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->or_like('nim', $q);
        $this->db->or_like('nama_mhs', $q);
        $this->db->or_like('tempat_lahir_mhs', $q);
        $this->db->or_like('tgl_lahir_mhs', $q);
        $this->db->or_like('gender_mhs', $q);
        $this->db->or_like('agama_mhs', $q);
        $this->db->or_like('sks_diakui', $q);
        $this->db->or_like('angkatan', $q);
        $this->db->or_like('nama_jurusan', $q);
        $this->db->or_like('nama_jenjang', $q);
        $this->db->or_like('foto_mhs', $q);
        $this->db->group_end();
        $this->db->where('status', '1');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mahasiswa_model.php */
/* Location: ./application/models/Mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-28 01:30:45 */
/* http://harviacode.com */